### ISSUE TITLE
No `develop' branch

### ISSUE THREAD

**Issue by stasinos** [mannkendall/Python#31]
In CONTRIBUTING, it is mentioned that PRs should target the `develop' branch, but there is no such branch in the repo. Please clarify.

**Comment by fpavogt** [comment]
Well spotted, @stasinos. Indeed, it looks like the contributing guidelines are no longer aligned with the state of the repository. I'll need to correct this (by adding the missing branches). Are you asking because you were considering to contribute to the project ?

**Comment by stasinos** [comment]
Yes, we are working on customizing your implementation for a specific need of ours, but there are also some patches falling out of this that you might want to consider for general use.

We will PR you soon, but if you want you can browse through the fork here:
https://github.com/data-eng/mannkendall
